name: rnd_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  hugeicons: ^0.0.7
  riverpod: ^2.6.1
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.14
  equatable: ^2.0.7
  riverpod_annotation: ^2.6.1
  firebase_database: ^11.2.0
  flutter_riverpod: ^2.6.1
  freezed: ^2.5.7
  collection: ^1.19.0
  firebase_auth: ^5.4.0
  shared_preferences: ^2.3.5
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  hive: ^2.2.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/lake_background.jpg
