name: Flutter Tests
on: push
jobs: 
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: subosito/flutter-action@v2
              with:
                  flutter-version: '3.27.0'
                  channel: 'stable'

            - name: Install dependencies
              run: flutter pub get

            - name: Activate globally junitreport
              run: dart pub global activate junitreport

            - name: Verify formatting
              run: dart format --set-exit-if-changed .

            - name: Analyze project
              run: flutter analyze || exit 1

            - name: Create test results directory
              run: mkdir -p build/test-results

            - name: Run tests and generate XML report
              run: flutter test --machine | tojunit --output build/test-results/test-output.xml

            - name: Upload test results
              uses: actions/upload-artifact@v3
              with:
                name: test-results
                path: build/test-results/test-output.xml

            - name: Run tests with coverage
              run: flutter test --coverage

            - name: Upload coverage report
              uses: actions/upload-artifact@v3
              with:
                name: coverage-report
                path: coverage/lcov.info
